import { NextSeo } from "next-seo";

import { SITE_URL } from "@/constants/constants";
import prisma from "@/lib/prisma";
import { Post } from "@prisma/client";

async function getPostByID(id: string) {
  const post = await prisma.post.findUnique({
    where: {
      id,
    },
  });
  return post;
}

type HeadProps = {
  params: { id: string };
};

export default async function Head({ params }: HeadProps) {
  const { id } = params;

  const post: Post | null = await getPostByID(id as string);

  const title = post?.title || "Poems By AI";
  const description =
    post?.content ||
    "Poems generated by OpenAI's GPT-3 language model. This website is investigating the capabilities of GPT-3 and how it can be used to generate poetry.";
  const url = `${SITE_URL}/poems/${id}`;

  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>{title}</title>
      <NextSeo
        title={title}
        description={description}
        canonical={url}
        openGraph={{
          url,
          title,
          description,
          images: [
            {
              url:
                post?.imageUrl ||
                "https://res.cloudinary.com/dmiizmobu/image/upload/v1668758334/openai-beauty/DALL_E_2022-11-18_08.57.24.png",
              width: 1600,
              height: 900,
              alt: title,
              type: "image/jpeg",
            },
          ],
          siteName: "OpenAI GPT-3 Poems",
        }}
      />
    </>
  );
}
