import { SEOComponent } from "@/components/SEOComponent";
import { SITE_URL } from "@/constants/constants";

export default function Head() {
  const title = "About Me";
  const description =
    "Poems generated by OpenAI's GPT-3 language model. This website is investigating the capabilities of GPT-3 and how it can be used to generate poetry.";
  const url = `${SITE_URL}/about`;

  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>About Me</title>
      <link
        rel="icon"
        href="https://res.cloudinary.com/dmiizmobu/image/upload/c_scale,w_64/v1668858555/openai-beauty/DALL_E_2022-11-19_12.46.31_-_Make_a_favicon_representing_AI_being_creative_monkey_pixels_2.png"
      />
      <SEOComponent title={title} description={description} siteUrl={url} />
    </>
  );
}
