import { SEOComponent } from "@/components/SEOComponent";
import { SITE_URL } from "@/constants/constants";

export default function Head() {
  const title = "About Me";
  const description =
    "Poems generated by OpenAI's GPT-3 language model. This website is investigating the capabilities of GPT-3 and how it can be used to generate poetry.";
  const url = `${SITE_URL}/about`;

  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>About Me</title>
      <SEOComponent title={title} description={description} siteUrl={url} />
    </>
  );
}
