import type { AppProps } from "next/app";
import { Yeseva_One, Josefin_Sans } from "@next/font/google";
import { DefaultSeo } from "next-seo";
import { SITE_URL } from "@/constants/constants";

const josefin = Josefin_Sans({
  weight: ["100"],
  subsets: ["latin"],
});

const yeseva = Yeseva_One({
  weight: ["400"],
  subsets: ["latin"],
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <style jsx global>
        {`
          :root {
            --josefin-font: ${josefin.style.fontFamily};
            --yeseva-font: ${yeseva.style.fontFamily};
          }
        `}
      </style>
      <Component {...pageProps} />
      <DefaultSeo
        openGraph={{
          url: SITE_URL,
          title: "OpenAI GPT-3 Poems",
          description:
            "Poems generated by OpenAI's GPT-3 language model. This website is investigating the capabilities of GPT-3 and how it can be used to generate poetry.",
          images: [
            {
              url: "https://res.cloudinary.com/dmiizmobu/image/upload/v1668758334/openai-beauty/DALL_E_2022-11-18_08.57.24.png",
              width: 1600,
              height: 900,
              alt: "Og Image Alt",
              type: "image/jpeg",
            },
          ],
          siteName: "OpenAI GPT-3 Poems",
        }}
        twitter={{
          handle: "@FrontEndDrake",
          site: "@FrontEndDrake",
          cardType: "summary_large_image",
        }}
      />
    </>
  );
}
