// SITE INFO Constants
export const SITE_NAME = "AI Poetry";

export const SITE_URL = "https://ai-poetry.com";

export const SITE_DESCRIPTION =
  "Poems generated by OpenAI's GPT-3 language model. This website is investigating the capabilities of GPT-3 and how it can be used to generate poetry.";

export const SITE_IMAGE =
  "https://res.cloudinary.com/dmiizmobu/image/upload/v1668758334/openai-beauty/DALL_E_2022-11-18_08.57.24.png";

export const SITE_ICON =
  "https://res.cloudinary.com/dmiizmobu/image/upload/c_scale,w_64/v1668858555/openai-beauty/DALL_E_2022-11-19_12.46.31_-_Make_a_favicon_representing_AI_being_creative_monkey_pixels_2.png";

export const TWITTER_HANDLE = "@FrontEndDrake";

// API Constants
export const API_URL_ENDPOINT =
  process.env.NODE_ENV === "production" ? SITE_URL : "http://localhost:3000";

// React Query Constants

export const RQ_USER_KEY = "user";
export const RQ_POSTS_KEY = "posts";
export const RQ_POST_KEY = "post";
