import { SEOComponent } from "@/components/SEOComponent";
import { SITE_URL } from "@/constants/constants";

export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Poems By AI</title>

      <link rel="canonical" href="https://www.chemify.io/technology"></link>
      <SEOComponent
        title="OpenAI GPT-3 Poems"
        description="Poems generated by OpenAI's GPT-3 language model. This website is investigating the capabilities of GPT-3 and how it can be used to generate poetry."
        siteUrl={SITE_URL}
      />
    </>
  );
}
