import { SEOComponent } from "@/components/SEOComponent";
import { SITE_URL } from "@/constants/constants";

export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Poems By AI</title>
      <link
        rel="icon"
        href="https://res.cloudinary.com/dmiizmobu/image/upload/c_scale,w_64/v1668858555/openai-beauty/DALL_E_2022-11-19_12.46.31_-_Make_a_favicon_representing_AI_being_creative_monkey_pixels_2.png"
      />
      <SEOComponent
        title="OpenAI GPT-3 Poems"
        description="Poems generated by OpenAI's GPT-3 language model. This website is investigating the capabilities of GPT-3 and how it can be used to generate poetry."
        siteUrl={SITE_URL}
      />
    </>
  );
}
