import React from "react";

export const LegalDisclaimer = () => {
  return (
    <section className="p-4 w-full mt-12">
      <h3 className="mb-2">Legal Disclaimer</h3>
      <p className="text-sm italic">
        All content on this site is generated by the OpenAI API and any content
        produced which is found to be a copy of another person&apos;s work is
        completely unintentional. If there is content on this site that you feel
        infringes on someone elses work then please contact the site owner and
        the content will be removed.
      </p>
    </section>
  );
};
