import React from "react";

import { trpc } from "@/utils/trpc";
import Head from "next/head";
import Layout from "@/layout/Layout";
import { SEOComponent } from "@/components/SEOComponent";
import { SITE_URL } from "@/constants/constants";
import { useRouter } from "next/router";
import { Loader } from "@/components/common/Loader";
import { Poem } from "@/components/Poem";

export default function PoemPage() {
  const router = useRouter();

  const {
    query: { id },
  } = router;

  const { data: post, isLoading } = trpc.poemRequest.getOne.useQuery({
    id: id as string,
  });

  const title = post?.title || "Poems By AI";
  const description =
    post?.content ||
    "Poems generated by OpenAI's GPT-3 language model. This website is investigating the capabilities of GPT-3 and how it can be used to generate poetry.";
  const url = `${SITE_URL}/poems/${id}`;

  return (
    <>
      <Head>
        <title>Poems By AI</title>
        <link
          rel="icon"
          href="https://res.cloudinary.com/dmiizmobu/image/upload/c_scale,w_64/v1668858555/openai-beauty/DALL_E_2022-11-19_12.46.31_-_Make_a_favicon_representing_AI_being_creative_monkey_pixels_2.png"
        />
        <SEOComponent
          title={title}
          description={description}
          siteUrl={url}
          imageUrl={post?.imageUrl}
        />
      </Head>
      <Layout>
        <section>
          {isLoading ? (
            <Loader loadingText="Loading..." />
          ) : (
            <>{post ? <Poem post={post} /> : <p>No post found</p>}</>
          )}
        </section>
      </Layout>
    </>
  );
}
